# Train settings Hyperparameters ---------------------------------------------------------------------------------------
epochs: 200  # number of epochs to train for
batch_size: 256 # number of images per batch (-1 for AutoBatch)
size: [64, 64]  # size of input images as integer or w,h
workers: 2 # number of worker threads for data loading (per RANK if DDP)
optimizer: Adam # optimizer to use, choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
lr0: 0.01  # initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
lrf: 0.00001  # final learning rate (lr0 * lrf)
momentum: 0.937  # SGD momentum/Adam beta1
warmup_epochs: 3.0  # warmup epochs (fractions ok)

# Augmentation ---------------------------------------------------------------------------------------------------------
augment: True
rot90: 0.5  # image rotation (+/- deg)
flipud: 0.5  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)
brightness: 0.5  # image brightness adjustment (probability)